Astog espionage add on
astog/BES pull request #3
Opened 2017-11-30 09:10 UTC by Azurency

Update from Astog, you can read more about it here https://github.com/Azurency/CQUI_Community-Edition/issues/234

2017-11-30 17:48 UTC, ricanuck commented
Credit where it is due. Right? It is not an update FROM astog.

2017-11-30 17:54 UTC, ricanuck requested changes
Credit has to go where it is due, no matter how much any person may disagree with any other. THAT is how open source works. "Stealing" code without shame and due credit is not acceptable (even if it is a few lines).

2017-11-30 18:16 UTC, ricanuck commented on UI/EspionageSupport.lua
> +        if district:IsComplete() and not district:IsPillaged() then
--ARISTOS: to only show available and valid targets in each city, both for espionage overview and selector

2017-11-30 18:17 UTC, ricanuck commented on UI/PartialScreens/EspionageOverview.lua
> +    if hasDistrict(city, districtType) then
--ARISTOS: make use of the espionagesupport.lua funtion, more efficient and has been fixed to only show valid targets

2017-11-30 18:18 UTC, ricanuck commented on UI/PartialScreens/EspionageOverview.lua
> -    local hasDistrict:boolean = false;
Erase all this, no need to leave it block commented.

2017-11-30 18:28 UTC, Azurency commented
Wow, I'm really sorry, I wrote Astog without even noticing (might be because I was in his repository). Of course I meant you Aristos, I corrected in the code also with your credits.

2017-11-30 18:29 UTC, ricanuck commented
Thanks.

2017-12-10 15:05 UTC, Azurency commented
We've merged this changes in CQUI.

2018-02-11 08:39 UTC, merged